package framework

/**
 * Defaults:
 * -> can be overridden at build time with -ldflags -X
 *
 * How to Override:
 * go build -ldflags "\
 * -X 'github.com/ikaitla/framework.EngineName=Ikaitla Engine' \
 * -X 'github.com/ikaitla/framework.EngineVersion=2026.02.03' \
 * -X 'github.com/ikaitla/framework.EngineTagline=Composable multi-profile CLI runtime' \
 * -X 'github.com/ikaitla/framework.RepoModulePath=github.com/emyassine/ikaitla' \
 * -X 'github.com/ikaitla/framework.ProfilePackageImportPath=github.com/ikaitla/framework/profile' \
 * -X 'github.com/ikaitla/framework.CmdProfilesImportBase=github.com/emyassine/ikaitla/cmd' \
 * -X 'github.com/ikaitla/framework.ProfileWiringOutputFile=generated.go' \
 * -X 'github.com/ikaitla/framework.MainRegistryOutputFile=generated_profiles.go' \
 * " -o bin/ikaitla .
 */

var (
	// RepoModulePath is the Go module path (from go.mod "module ...").
	// If empty, tools/generate.go will auto-detect it from go.mod.
	RepoModulePath = ""

	// ProfilePackageImportPath is the import path for the engine profile package.
	// If empty, tools/generate.go will derive it from RepoModulePath:
	//   RepoModulePath + "/framework/profile"
	ProfilePackageImportPath = ""

	// CmdProfilesImportBase is the import base for profiles entrypoints.
	// If empty, tools/generate.go will derive it from RepoModulePath:
	//   RepoModulePath + "/cmd"
	CmdProfilesImportBase = ""

	// Output filenames (no hardcode in generator)
	ProfileWiringOutputFile = "generated.go"
	MainRegistryOutputFile  = "generated_profiles.go"

	// Template: per-profile wiring (cmd/<profile>/generated.go)
	// UPDATED: Now includes shared commands
	TemplateProfileWiring = `// Code generated by ikaitla. DO NOT EDIT.
//
// Engine: {{.EngineName}} {{.EngineVersion}}
// Profile: {{.ProfileName}}
package {{.Package}}

import (
		profile "{{.ProfileImportPath}}"
		"{{.SharedImportPath}}"
)

// Execute runs the {{.ProfileName}} profile
func Execute() {
		root := profile.NewRootCommand(Metadata)

		// Auto-discovered commands
{{- range .Commands}}
		root.AddCommand({{.}}())
{{- end}}

		// Shared commands (available in all profiles)
		root.AddCommand(shared.NewVersionCmd(Metadata.Version))
		root.AddCommand(shared.NewDoctorCmd())

		profile.ExecuteProfile(root)
}
`

	// Template: main registry (generated_profiles.go)
	TemplateMainRegistry = `// Code generated by ikaitla. DO NOT EDIT.
//
// Engine: {{.EngineName}} {{.EngineVersion}}
package main

import (
{{- range .Profiles}}
		{{.ImportAlias}} "{{.ImportPath}}"
{{- end}}
)

func init() {
{{- range .Profiles}}
		profileRegistry["{{.Name}}"] = {{.ImportAlias}}.Execute
{{- if .Aliases}}
{{- range .Aliases}}
		profileRegistry["{{.}}"] = {{.ImportAlias}}.Execute
{{- end}}
{{- end}}
{{- end}}
}
`
)
